### ISSUE TITLE
Icons don’t display for Office 2019

### ISSUE THREAD

**Issue by dlwilson008** [maltehi/outlook-taskboard#14]
Set this up on Windows 10 and Office 2019. The functionality all seems to be there, but the icons don’t appear. You can still click the buttons, but without knowing where the buttons are, you wouldn’t know where to click, or if new, that any buttons actually existed.

**Comment by maltehi** [comment]
Hi, thanks for the feedback. I can't test this myself unfortunately, as I don't have Office 2019 yet... Does the display work properly in Internet Explorer?

**Comment by dlwilson008** [comment]
Hey!

Sorry I’ve taken so long to reply. I’ve not yet tested on IE on those
machines, so not sure. I’ll let you know when I get a chance.

I do use this at work though, and it’s amazing!

Quick question: for the “Restrict” option, is there any guidance on syntax
for applying filters?

Thanks!

David

**Comment by ErikLevin** [comment]
@dlwilson008 Sorry if I'm digging up an old issue, but if it is still relevant to you, did you download the released .zip or did you clone the repo?

I had the same issue and discovered that in my case the problem was i git cloned the repo with Unix line endings. Fixing the line endings to Windows (cr lf) resolved the problem.

**Comment by dlwilson008** [comment]
@ErikLevin Thanks! And while it’s an old issue, it’s still relevant and still an issue! I’m not sure I know how to fix it based on your instructions (I’m not a developer), but I get what you are saying and can probably figure it out. Thanks so much for the reply!!

**Comment by maltehi** [comment]
Were you able to fix the line ending? Did it fix the issue?

**Comment by dlwilson008** [comment]
> Were you able to fix the line ending? Did it fix the issue?

Haven't tried it yet. With COVID haven't been back to the offices to try it out. But I appreciate the update and look forward to testing it out!

**Comment by maltehi** [comment]
I finally got to test it in Outlook 2019, and didn't see any problems. Let us know if the line ending thing helped!
