### ISSUE TITLE
Enhancement: Toggle color mode for outlook color themes

### ISSUE THREAD

**Issue by tallguyjenks** [maltehi/outlook-taskboard#15]
the default is the white mode, but the new dark grey mode is what i use so its a little jarring  since everything i do is in dark mode, allow an option that can change the CSS background colors to match the themes?

✔️Default  
❌Dark Mode: `background: #6A6A6A`

**Comment by tallguyjenks** [comment]
i manually edited the file for myself, but for other uses, a simple toggle button would be great to switch the background of the `<body>`

**Comment by maltehi** [comment]
> i manually edited the file for myself, but for other uses, a simple toggle button would be great to switch the background of the `<body>`

Hi, thanks for the suggestion. I now started working on this, but could use some input for how to define the colors. Did you change any other colors except the `<body>`?

**Comment by tallguyjenks** [comment]
@maltehi 
i personally did not change anything else other than the background color of the `<body>` element in `taskboard.css` 

the only addditional code was:

`background: #6A6A6A;` to 

```css
body{
    width: 100%;
    height: 100%;
    font: 400 12px/1.6 "Segoe UI", Tahoma, Arial, sans-serif;
    background: #6A6A6A;
}
```

**the difference**:

![1](https://user-images.githubusercontent.com/29872822/73702082-6fa4bb80-46a0-11ea-97fa-fb8cb33930e7.PNG)

![2](https://user-images.githubusercontent.com/29872822/73702083-6fa4bb80-46a0-11ea-9538-6d66c9a605b4.PNG)



the theming could be better but i havent gotten around to playing with this at all, i just made it easier on my eyes and left it at that so far

**Comment by maltehi** [comment]
Ok, nice. I have started implementing the dark theme on the branch `dark-mode` (see #16). I also changed the color of the lanes. I have not integrated a switch for toggling the mode yet, though, so it is still on a separate branch.
