### ISSUE TITLE
Confirmed working for Win 7 w/ MS Office Pro Plus 2013

### ISSUE THREAD

**Issue by NewMC** [maltehi/outlook-taskboard#7]
Thanks all for the good work on this, I can confirm full functionality on Windows 7 (64-bit) with MS Office Pro Plus 2013 (32-bit). I used the method where I replaced my home page location for my main account folder, but also works in IE and Chrome (with IE Tab extension) once ActiveX controls are enabled.

A couple things I've noticed, and I'm sure I can probably modify for my needs, just either haven't found the setting or dove into the code yet.

1) If you deactivate the 'Next' folder you do not see new tasks. I do not use Next so I've changed the title of Next to In Progress and disabled the In Progress folder. What determines the default folder where new tasks are created or sorted to by default?

2) I would suggest adding a setting which provides the ability to remove the Reminder info within the task list items.  I have commented this out on my end for now, may try to add a setting when I have some time.

3) Off topic (Outlook specific): Do you happen to know of a switch/setting in Outlook that will permanently allow access, so that you can avoid the frequent "Allow access" notification? By default, the maximum duration that can be allowed is 10 minutes, at which time you must approve again.

Thanks again! This will really streamline my workflow and I've already eliminated the Meistertask, Notion.so, and OneNote kanban boards that I was using.

**Comment by maltehi** [comment]
Hi! Thanks for your feedback and the hint with the Chrome extension. Will give that a try too.

About the other points:

1. This has just been partly addressed by a pull request, so tasks that are created using the button on the Backlog column will also appear in that column. Where tasks show up is determined by the status that they have assigned in Outlook. This is the "Not started" status by default, which is assigned to the Next column. But now, if you create a task in the Backlog column, it is assigned the "Deferred" status on creation and gets added to that column. Maybe we could also add a "New Task" button to the In Progress column, so you can create tasks directly there.

2. Good idea, that would be a nice feature.

3. Sadly, no. I still haven't been able to figure out what even causes these notifications. Most of the time they don't appear on my computer, but sometimes they just keep coming.

**Comment by NewMC** [comment]
Thanks for the response!

Same for me on #3, for a couple days it was asking every 10 minutes, but that has mostly stopped after a couple days of use.

I'm really enjoying this as it is by far the best, and most customizable, task management app for me to use on a secure work network in a MS Exchange environment.  Thanks again!

**Comment by maltehi** [comment]
The points from the original issue are now addressed in #10 and #11.
