### ISSUE TITLE
Feature request: Multiple "Tasks" folders with individual kanbans

### ISSUE THREAD

**Issue by EasyPP** [maltehi/outlook-taskboard#8]
I am trying to create multiple task folders which are all individual projects with own kanban.

Also this task-folder with configuration should be shareable with my collegues.

Is this doable?

I am happy to help out, but please provide some pointers to what is needed to get this working.

Best

**Comment by maltehi** [comment]
Hi!

Just from the top of my mind... I think right now it would be possible to switch between projects by changing all the folder locations in the config. Of course that's not very convenient or useful if you want to use multiple projects in parallel. So, basically I think it would be necessary to handle several config instances in parallel. Maybe one could create a separate copy of kanban.html for each project and then address the corresponding configurations by individual names from there. Not sure if that makes sense.... But might be an idea. 

Best regards
